import type { Theme } from "./types";

// ─── Bibliothèque de thèmes globaux ──────────────────────
export const themes: Theme[] = [
  {
    id: "business",
    name: "Business",
    description: "Professionnel et sobre, idéal pour les entreprises",
    preview: "💼",
    colors: {
      primary: "#0F172A",
      secondary: "#1E293B",
      accent: "#3B82F6",
      background: "#FFFFFF",
      text: "#0F172A",
      cardBg: "#F8FAFC",
      cardBorder: "#E2E8F0",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "12px",
    shadows: "0 4px 6px -1px rgba(0,0,0,0.1)",
  },
  {
    id: "premium",
    name: "Premium",
    description: "Élégant et raffiné, pour les marques haut de gamme",
    preview: "✨",
    colors: {
      primary: "#1E1B4B",
      secondary: "#312E81",
      accent: "#818CF8",
      background: "#FAFAFA",
      text: "#1E1B4B",
      cardBg: "#FFFFFF",
      cardBorder: "#E0E7FF",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "16px",
    shadows: "0 10px 25px -5px rgba(0,0,0,0.1)",
  },
  {
    id: "luxe",
    name: "Luxe",
    description: "Sophistiqué et luxueux, pour les marques de luxe",
    preview: "👑",
    colors: {
      primary: "#0C0A09",
      secondary: "#1C1917",
      accent: "#D4AF37",
      background: "#FAFAF9",
      text: "#0C0A09",
      cardBg: "#FFFFFF",
      cardBorder: "#E7E5E4",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "8px",
    shadows: "0 20px 40px -10px rgba(0,0,0,0.15)",
  },
  {
    id: "moderne",
    name: "Moderne",
    description: "Design contemporain et dynamique",
    preview: "🎨",
    colors: {
      primary: "#0F172A",
      secondary: "#334155",
      accent: "#06B6D4",
      background: "#FFFFFF",
      text: "#0F172A",
      cardBg: "#F0FDFA",
      cardBorder: "#CCFBF1",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "20px",
    shadows: "0 8px 30px -4px rgba(0,0,0,0.08)",
  },
  {
    id: "minimaliste",
    name: "Minimaliste",
    description: "Épuré et simple, l'essentiel en moins",
    preview: "◻️",
    colors: {
      primary: "#111827",
      secondary: "#374151",
      accent: "#111827",
      background: "#FFFFFF",
      text: "#111827",
      cardBg: "#F9FAFB",
      cardBorder: "#F3F4F6",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "4px",
    shadows: "none",
  },
  {
    id: "creatif",
    name: "Créatif",
    description: "Coloré et expressif, pour les créatifs",
    preview: "🎭",
    colors: {
      primary: "#1E1B4B",
      secondary: "#4338CA",
      accent: "#F59E0B",
      background: "#FFFBEB",
      text: "#1E1B4B",
      cardBg: "#FFFFFF",
      cardBorder: "#FDE68A",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "24px",
    shadows: "0 12px 40px -8px rgba(0,0,0,0.12)",
  },
  {
    id: "corporate",
    name: "Corporate",
    description: "Sérieux et structuré, pour les grandes entreprises",
    preview: "🏢",
    colors: {
      primary: "#0F172A",
      secondary: "#1E293B",
      accent: "#2563EB",
      background: "#FFFFFF",
      text: "#0F172A",
      cardBg: "#F1F5F9",
      cardBorder: "#CBD5E1",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "8px",
    shadows: "0 4px 12px -2px rgba(0,0,0,0.08)",
  },
  {
    id: "boutique",
    name: "Boutique",
    description: "Chaleureux et accueillant, pour les boutiques",
    preview: "🛍️",
    colors: {
      primary: "#7C2D12",
      secondary: "#9A3412",
      accent: "#EA580C",
      background: "#FFFBEB",
      text: "#431407",
      cardBg: "#FFFFFF",
      cardBorder: "#FED7AA",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "16px",
    shadows: "0 8px 24px -4px rgba(0,0,0,0.1)",
  },
  {
    id: "restaurant",
    name: "Restaurant",
    description: "Chaleureux et gourmand, pour la restauration",
    preview: "🍽️",
    colors: {
      primary: "#1C1917",
      secondary: "#292524",
      accent: "#DC2626",
      background: "#FFFBEB",
      text: "#1C1917",
      cardBg: "#FFFFFF",
      cardBorder: "#FEE2E2",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "16px",
    shadows: "0 8px 24px -4px rgba(0,0,0,0.1)",
  },
  {
    id: "portfolio",
    name: "Portfolio",
    description: "Élégant et visuel, pour les créatifs",
    preview: "🎨",
    colors: {
      primary: "#0F172A",
      secondary: "#1E293B",
      accent: "#8B5CF6",
      background: "#FFFFFF",
      text: "#0F172A",
      cardBg: "#F5F3FF",
      cardBorder: "#DDD6FE",
    },
    fonts: { heading: "Inter", body: "Inter" },
    borderRadius: "20px",
    shadows: "0 12px 40px -8px rgba(0,0,0,0.1)",
  },
];

// ─── Obtenir un thème par ID ─────────────────────────────
export function getTheme(id: string): Theme | undefined {
  return themes.find((t) => t.id === id);
}

// ─── Obtenir tous les thèmes ─────────────────────────────
export function getAllThemes(): Theme[] {
  return themes;
}